export const cartoes= [
    { id :  1 ,	name : "TAM Itaucard 2.0 International MasterCard" ,	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  2 ,	name : "TAM Itaucard 2.0 International Visa" ,	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  3 ,	name : "TAM Itaucard 2.0 Gold Visa" ,	valPonto: 1.33 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  4 ,	name : "TAM Itaucard 2.0 Gold MasterCard" , 	valPonto: 1.33 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  5 ,	name : "TAM Itaucard 2.0 Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  6 ,	name : "TAM Itaucard 2.0 Platinum Visa" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  7 ,	name : "TudoAzul Itaucard 2.0 International Mastercard (Compras comuns)" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  8 ,	name : "TudoAzul Itaucard 2.0 International Mastercard (Compras passagens azul)" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  9 ,	name : "TudoAzul Itaucard 2.0 Gold MasterCard (Compras comuns)" , 	valPonto: 1.33 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  10 ,	name : "TudoAzul Itaucard 2.0 Gold MasterCard (Compras passagens azul)" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  11 ,	name : "TudoAzul Itaucard 2.0 Platinum MasterCard (Compras comuns)" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  12 ,	name : "TudoAzul Itaucard 2.0 Platinum MasterCard (Compras passagens azul)" , 	valPonto: 2.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  13 ,	name : "Itaú Múltiplo Internacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  14 ,	name : "Itaucard 2.0 Internacional Programa Sempre Presente MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  15 ,	name : "Itaucard 2.0 Internacional Programa Sempre Presente Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  16 ,	name : "Itaucard 2.0 Gold Programa Sempre Presente MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  17 ,	name : "Itaucard 2.0 Gold Programa Sempre Presente Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  18 ,	name : "Itaucard 2.0 Platinum Programa Sempre Presente MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  19 ,	name : "Itaucard 2.0 Platinum Programa Sempre Presente Visa " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  20 ,	name : "Itaucard MasterCard Black" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  21 ,	name : "Itaucard Visa Infinite" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  22 ,	name : "Itaú Visa Infinite" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  23 ,	name : "Itaú MasterCard Black" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  24 ,	name : "Itaú MasterCard Platinum" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  25 ,	name : "Itaucard Universitário MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  26 ,	name : "Itaucard Universitário Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  27 ,	name : "Itaú Uniclass Múltiplo Internacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  28 ,	name : "Itaú Uniclass Múltiplo Internacional Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  29 ,	name : "Itaú Uniclass Múltiplo Gold MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  30 ,	name : "Itaú Uniclass Múltiplo Gold Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  31 ,	name : "Itaú Uniclass Internacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  32 ,	name : "Itaú Uniclass Internacional Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  33 ,	name : "Itaú Uniclass Gold MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  34 ,	name : "Itaú Uniclass Gold Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  35 ,	name : "Itaú Uniclass Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  36 ,	name : "Itaú Uniclass Platinum Visa " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  37 ,	name : "Itaú Personnalité Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  38 ,	name : "Itaú Personnalité Platinum Visa" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  39 ,	name : "Itaú Personnalité MasterCard Black" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  40 ,	name : "Itaú Múltiplo Gold MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  41 ,	name : "TAM Itaucard Nacional Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  42 ,	name : "TAM Itaucard Nacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  43 ,	name : "Banco do Brasil Smiles International MasterCard" , 	valPonto: 1.35 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  44 ,	name : "Banco do Brasil Smiles Gold MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 0},
    { id :  45 ,	name : "Banco do Brasil Smiles Platinum MasterCard" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  46 ,	name : "Ourocard Platinum Visa (Compras até R$ 4 mil)" , 	valPonto: 1.2 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  47 ,	name : "Ourocard Platinum MasterCard (Compras acima de R$ 4 mil)" , 	valPonto: 1.2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  48 ,	name : "Ourocard Platinum Amex" , 	valPonto: 1.6 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  49 ,	name : "Ourocard Mastercard Black " , 	valPonto: 2 ,	validadePontos: 0 ,	valPontos: 24},
    { id :  50 ,	name : "Ourocard Visa Infinite " , 	valPonto: 2 ,	validadePontos: 0 ,	valPontos: 36},
    { id :  51 ,	name : "Ourocard Gold Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  52 ,	name : "Ourocard Gold MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  53 ,	name : "Ourocard International Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  54 ,	name : "Ourocard International MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  55 ,	name : "Ourocard Doméstico Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  56 ,	name : "Ourocard Doméstico MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  57 ,	name : "Ourocard Elo Mais" , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  58 ,	name : "Ourocard Elo Grafite" , 	valPonto: 1.4 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  59 ,	name : "Ourocard Estilo Elo Grafite" , 	valPonto: 1.7 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  60 ,	name : "Ourocard Estilo Platinum Visa" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 24},
    { id :  61 ,	name : "Ourocard Estilo Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  62 ,	name : "Ourocard Amex Platinum Estilo" , 	valPonto: 1.6 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  63 ,	name : "Ourocard Estilo Elo Nanquim" , 	valPonto: 2.2 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  64 ,	name : "Ourocard Elo Nanquim" , 	valPonto: 2.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  65 ,	name : "Ourocard Elo " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  66 ,	name : "Bradesco Smiles Gold" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  67 ,	name : "Bradesco Smiles Platinum" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  68 ,	name : "Bradesco Smiles Internacional" , 	valPonto: 1.35 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  69 ,	name : "Bradesco Master Gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  70 ,	name : "Bradesco Visa Gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  71 ,	name : "Bradesco Master Platinum" , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  72 ,	name : "Bradesco Visa Platinum" , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  73 ,	name : "Bradesco Visa Infinite (Compras até R$ 9 mil)" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  74 ,	name : "Bradesco Visa Infinite (Compras acima de R$ 9 mil)" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  75 ,	name : "Bradesco Mastercard Black (Compras até R$ 9 mil)" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  76 ,	name : "Bradesco Mastercard Black (Compras acima de R$ 9 mil)" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  77 ,	name : "Bradesco Elo Mais " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 0},
    { id :  78 ,	name : "Bradesco Exclusive Elo Mais " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 36},
    { id :  79 ,	name : "Bradesco Exclusive Gold American Express " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  80 ,	name : "Bradesco Visa Gold Exclusive " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  81 ,	name : "Bradesco Prime Visa Gold " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  82 ,	name : "Bradesco MasterCard Gold Exclusive " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  83 ,	name : "Bradesco Prime MasterCard Gold " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  84 ,	name : "Bradesco Prime Platinum American Express " , 	valPonto: 1.7 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  85 ,	name : "Bradesco Prime Visa Platinum " , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  86 ,	name : "Bradesco Prime MasterCard Platinum " , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  87 ,	name : "Bradesco Prime MasterCard Black (Gastos de até R$ 9 mil )" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  88 ,	name : "Bradesco Prime MasterCard Black (Gastos acima de 9 mil )" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  89 ,	name : "Bradesco Prime Visa Infinite (Gastos de até R$ 9 mil )" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  90 ,	name : "Bradesco Prime Visa Infinite (Gastos acima de 9 mil )" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  91 ,	name : "Bradesco Preferencial Gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  92 ,	name : "Bradesco Prime Platinum Múltiplo " , 	valPonto: 1.6 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  93 ,	name : "Bradesco Multiplo Infinite Prime (Gastos até 9 mil)" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  94 ,	name : "Bradesco Multiplo Infinite Prime (Gastos acima de 9 mil)" , 	valPonto: 2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  95 ,	name : "Bradesco Gold American Express " , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  96 ,	name : "Bradesco Platinum American Express " , 	valPonto: 1.4 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  97 ,	name : "Santander Gold Visa " , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  98 ,	name : "Santander Gold MasterCard " , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  99 ,	name : "Santander Light MasterCard " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  100 ,	name : "Santander Light Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  101 ,	name : "Santander Internacional Visa " , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  102 ,	name : "Santander Internacional MasterCard " , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  103 ,	name : "Santander Free MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  104 ,	name : "Santander Free Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  105 ,	name : "Santander Flex Nacional" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  106 ,	name : "Santander Platinum MasterCard " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  107 ,	name : "Santander Platinum Visa " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  108 ,	name : "Santander Platinum Style MasterCard " , 	valPonto: 1.3 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  109 ,	name : "Santander Platinum Style Visa " , 	valPonto: 1.3 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  110 ,	name : "Santander Elite Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  111 ,	name : "Santander Elite Platinum Visa " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  112 ,	name : "Santander Unlimited Visa Infinite " , 	valPonto: 2.2 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  113 ,	name : "Santander Unlimited Mastercard Black" , 	valPonto: 2.2 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  114 ,	name : "Ferrari Santander MasterCard" , 	valPonto: 1.2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  115 ,	name : "Santander Flex Internacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  116 ,	name : "Santander Flex Internacional Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  117 ,	name : "Santander OAB SP MasterCard" , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  118 ,	name : "Santander Dufry Platinum MasterCard" , 	valPonto: 1.5 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  119 ,	name : "Santander Dufry Platinum Visa " , 	valPonto: 1.5 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  120 ,	name : "Santander Unique " , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  121 ,	name : "Santander Fit " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  122 ,	name : "Santander Nacional " , 	valPonto: 1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  123 ,	name : "HSBC Open Card Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  124 ,	name : "HSBC Open Card MasterCard " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  125 ,	name : "HSBC Open Card Amex " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  126 ,	name : "HSBC SuperClass Card Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  127 ,	name : "HSBC SuperClass Card MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  128 ,	name : "HSBC Gold Card Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  129 ,	name : "HSBC Platinum HSBC Advance MasterCard " , 	valPonto: 1.3 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  130 ,	name : "HSBC Platinum HSBC Advance Visa " , 	valPonto: 1.3 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  131 ,	name : "HSBC Platinum Visa" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  132 ,	name : "HSBC Auto Gold Card Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  133 ,	name : "HSBC Premier MasterCard" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  134 ,	name : "HSBC Premier Mastecard Black (Transação nacional)" , 	valPonto: 2 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  135 ,	name : "HSBC Premier Mastecard Black (Transação internacional )" , 	valPonto: 3 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  136 ,	name : "HSBC Delta Sky Miles Visa (Transação Nacional e internacional) " , 	valPonto: 1 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  137 ,	name : "HSBC Delta Sky Miles Visa (Compra de passagens aéreas Delta)" , 	valPonto: 2 ,	validadePontos: 0  ,	valPontos: 0},
    { id :  138 ,	name : "Instituto HSBC Solidariedade Visa " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  139 ,	name : "Instituto HSBC Solidariedade MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  140 ,	name : "Banrisul Visa Classic" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  141 ,	name : "Banrisul Visa Platinum" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  142 ,	name : "Banrisul Visa Gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  143 ,	name : "Banrisul Mastercard Platinum" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  144 ,	name : "Banrisul Visa Infinite" , 	valPonto: 2.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  145 ,	name : "Banrisul MasterCard Standard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  146 ,	name : "Banrisul Mastercard Gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  147 ,	name : "Banrisul Visa Gold Servidor Público" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  148 ,	name : "Banrisul MasterCard Gold Servidor Público" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  149 ,	name : "Banrisul MasterCard Standard Servidor Público" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  150 ,	name : "Banrisul Visa Universitário " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  151 ,	name : "Banrisul MasterCard Universitário" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  152 ,	name : "Banrisul Visa Classic Servidor Público " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  153 ,	name : "Caixa Turismo Internacional" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  154 ,	name : "Caixa gold" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  155 ,	name : "Caixa Platinum" , 	valPonto: 1.35 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  156 ,	name : "Caixa Visa Infinite" , 	valPonto: 2.1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  157 ,	name : "Caixa Mastercard Black " , 	valPonto: 2.1 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  158 ,	name : "Caixa Cartão Azul " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  159 ,	name : "Caixa Internacional " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  160 ,	name : "Caixa Platinum Turismo (Gastos nos ramos de turismo e entretenimento)" , 	valPonto: 1.8 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  161 ,	name : "Caixa Platinum Turismo (Gastos nos demais estabelecimentos)" , 	valPonto: 1.35 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  162 ,	name : "Epidemia Corinthiana CAIXA Platinum" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  163 ,	name : "Citibank Aadvantage International Visa " , 	valPonto: 1 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  164 ,	name : "Citibank Aadvantage International MasterCard" , 	valPonto: 1 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  165 ,	name : "Citibank Advantage Gold Visa " , 	valPonto: 1 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  166 ,	name : "Citibank Aadvantage Gold MasterCard " , 	valPonto: 1 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  167 ,	name : "Citibank Aadvantage Platinum Visa " , 	valPonto: 1.3 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  168 ,	name : "Citibank Aadvantage Platinum MasterCard" , 	valPonto: 1.3 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  169 ,	name : "Citibank Aadvantage Black MasterCard " , 	valPonto: 1.5 ,	validadePontos: 0 ,	valPontos: 0},
    { id :  170 ,	name : "Diners Club Internacional Exclusive" , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  171 ,	name : "Diners Club Internacional" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  172 ,	name : "Diners Club Internacional Exclusive Exame " , 	valPonto: 1.5 ,	validadePontos: 36 ,	valPontos: 36},
    { id :  173 ,	name : "Diners Club Internacional Exame " , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  174 ,	name : "Banco Votorantim Internacional Visa" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  175 ,	name : "Banco Votorantim Internacional MasterCard" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  176 ,	name : "Banco Votorantim Platinum Visa  (Gasto de até R$ 1 mil)" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  177 ,	name : "Banco Votorantim Platinum MasterCard (Gasto de até R$ 1 mil)" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  178 ,	name : "Banco Votorantim Platinum Visa (Gasto de R$ 1 mil a 2 mil)" , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  179 ,	name : "Banco Votorantim Platinum MasterCard (Gasto de R$ 1 mil a 2 mil) " , 	valPonto: 1.5 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  180 ,	name : "Banco Votorantim Platinum Visa (Gasto a partir de R$ 2 mil)" , 	valPonto: 1.75 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  181 ,	name : "Banco Votorantim Platinum MasterCard (Gasto a partir de R$ 2 mil)" , 	valPonto: 1.75 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  182 ,	name : "Banco Votorantim Gold Visa (Gasto de até R$ 1 mil)" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  183 ,	name : "Banco Votorantim Gold MasterCard (Gasto de até R$ 1 mil)" , 	valPonto: 1 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  184 ,	name : "Banco Votorantim Gold Visa (Gasto a partir de R$ 2 mil)" , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  185 ,	name : "Banco Votorantim Gold MasterCard (Gasto a partir de R$ 2 mil)" , 	valPonto: 1.2 ,	validadePontos: 24 ,	valPontos: 24},
    { id :  186 ,	name : "American Express® Green" , 	valPonto: 1.3 ,	validadePontos: 0  ,	valPontos: 0},
    { id :  187 ,	name : "American Express® Gold Card" , 	valPonto: 1.5 ,	validadePontos: 0  ,	valPontos: 0},
    { id :  188 ,	name : "The Platinum Card®" , 	valPonto: 2.2 ,	validadePontos: 0  ,	valPontos: 0},
    { id :  189 ,	name : "American Express® Credit" , 	valPonto: 1 ,	validadePontos: 0  ,	valPontos: 0},
    { id :  190 ,	name : "Bradesco American Express® Credit" , 	valPonto: 1 ,	validadePontos: 0  ,	valPontos: 0},
    
];